// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.Turso
{
    [EnumType]
    public readonly struct DatabaseSeedType : IEquatable<DatabaseSeedType>
    {
        private readonly string _value;

        private DatabaseSeedType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// Uses an database to seed the new database.
        /// </summary>
        public static DatabaseSeedType Database { get; } = new DatabaseSeedType("database");
        /// <summary>
        /// Uses a database dump to seed the new database.
        /// </summary>
        public static DatabaseSeedType Dump { get; } = new DatabaseSeedType("dump");

        public static bool operator ==(DatabaseSeedType left, DatabaseSeedType right) => left.Equals(right);
        public static bool operator !=(DatabaseSeedType left, DatabaseSeedType right) => !left.Equals(right);

        public static explicit operator string(DatabaseSeedType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DatabaseSeedType other && Equals(other);
        public bool Equals(DatabaseSeedType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
