// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package turso

import (
	"context"
	"reflect"

	"errors"
	"github.com/celest-dev/pulumi-turso/sdk/go/turso/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// An authentication token for a Turso database. Tokens can be used to connect to the database with specific permissions.
type DatabaseToken struct {
	pulumi.CustomResourceState

	// The authorization level for the token. Defaults to full-access if not specified.
	Authorization DatabaseTokenAuthorizationPtrOutput `pulumi:"authorization"`
	// The name of the database to create the token for.
	Database pulumi.StringOutput `pulumi:"database"`
	// The duration until the token expires (e.g., '24h', '7d', '30d'). If not specified, the token will not expire.
	Expiration pulumi.StringPtrOutput `pulumi:"expiration"`
	// The RFC3339 timestamp when the token expires, if an expiration was set.
	ExpiresAt pulumi.StringPtrOutput `pulumi:"expiresAt"`
	// List of databases that can be attached for read operations using this token.
	ReadAttach pulumi.StringArrayOutput `pulumi:"readAttach"`
	// The JWT token used to authenticate with the database.
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewDatabaseToken registers a new resource with the given unique name, arguments, and options.
func NewDatabaseToken(ctx *pulumi.Context,
	name string, args *DatabaseTokenArgs, opts ...pulumi.ResourceOption) (*DatabaseToken, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Database == nil {
		return nil, errors.New("invalid value for required argument 'Database'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DatabaseToken
	err := ctx.RegisterResource("turso:index:DatabaseToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDatabaseToken gets an existing DatabaseToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDatabaseToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DatabaseTokenState, opts ...pulumi.ResourceOption) (*DatabaseToken, error) {
	var resource DatabaseToken
	err := ctx.ReadResource("turso:index:DatabaseToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DatabaseToken resources.
type databaseTokenState struct {
}

type DatabaseTokenState struct {
}

func (DatabaseTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseTokenState)(nil)).Elem()
}

type databaseTokenArgs struct {
	// The authorization level for the token. Defaults to full-access if not specified.
	Authorization *DatabaseTokenAuthorization `pulumi:"authorization"`
	// The name of the database to create the token for.
	Database string `pulumi:"database"`
	// The duration until the token expires (e.g., '24h', '7d', '30d'). If not specified, the token will not expire.
	Expiration *string `pulumi:"expiration"`
	// List of databases that can be attached for read operations using this token.
	ReadAttach []string `pulumi:"readAttach"`
}

// The set of arguments for constructing a DatabaseToken resource.
type DatabaseTokenArgs struct {
	// The authorization level for the token. Defaults to full-access if not specified.
	Authorization DatabaseTokenAuthorizationPtrInput
	// The name of the database to create the token for.
	Database pulumi.StringInput
	// The duration until the token expires (e.g., '24h', '7d', '30d'). If not specified, the token will not expire.
	Expiration pulumi.StringPtrInput
	// List of databases that can be attached for read operations using this token.
	ReadAttach pulumi.StringArrayInput
}

func (DatabaseTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*databaseTokenArgs)(nil)).Elem()
}

type DatabaseTokenInput interface {
	pulumi.Input

	ToDatabaseTokenOutput() DatabaseTokenOutput
	ToDatabaseTokenOutputWithContext(ctx context.Context) DatabaseTokenOutput
}

func (*DatabaseToken) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseToken)(nil)).Elem()
}

func (i *DatabaseToken) ToDatabaseTokenOutput() DatabaseTokenOutput {
	return i.ToDatabaseTokenOutputWithContext(context.Background())
}

func (i *DatabaseToken) ToDatabaseTokenOutputWithContext(ctx context.Context) DatabaseTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseTokenOutput)
}

// DatabaseTokenArrayInput is an input type that accepts DatabaseTokenArray and DatabaseTokenArrayOutput values.
// You can construct a concrete instance of `DatabaseTokenArrayInput` via:
//
//	DatabaseTokenArray{ DatabaseTokenArgs{...} }
type DatabaseTokenArrayInput interface {
	pulumi.Input

	ToDatabaseTokenArrayOutput() DatabaseTokenArrayOutput
	ToDatabaseTokenArrayOutputWithContext(context.Context) DatabaseTokenArrayOutput
}

type DatabaseTokenArray []DatabaseTokenInput

func (DatabaseTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseToken)(nil)).Elem()
}

func (i DatabaseTokenArray) ToDatabaseTokenArrayOutput() DatabaseTokenArrayOutput {
	return i.ToDatabaseTokenArrayOutputWithContext(context.Background())
}

func (i DatabaseTokenArray) ToDatabaseTokenArrayOutputWithContext(ctx context.Context) DatabaseTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseTokenArrayOutput)
}

// DatabaseTokenMapInput is an input type that accepts DatabaseTokenMap and DatabaseTokenMapOutput values.
// You can construct a concrete instance of `DatabaseTokenMapInput` via:
//
//	DatabaseTokenMap{ "key": DatabaseTokenArgs{...} }
type DatabaseTokenMapInput interface {
	pulumi.Input

	ToDatabaseTokenMapOutput() DatabaseTokenMapOutput
	ToDatabaseTokenMapOutputWithContext(context.Context) DatabaseTokenMapOutput
}

type DatabaseTokenMap map[string]DatabaseTokenInput

func (DatabaseTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseToken)(nil)).Elem()
}

func (i DatabaseTokenMap) ToDatabaseTokenMapOutput() DatabaseTokenMapOutput {
	return i.ToDatabaseTokenMapOutputWithContext(context.Background())
}

func (i DatabaseTokenMap) ToDatabaseTokenMapOutputWithContext(ctx context.Context) DatabaseTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DatabaseTokenMapOutput)
}

type DatabaseTokenOutput struct{ *pulumi.OutputState }

func (DatabaseTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DatabaseToken)(nil)).Elem()
}

func (o DatabaseTokenOutput) ToDatabaseTokenOutput() DatabaseTokenOutput {
	return o
}

func (o DatabaseTokenOutput) ToDatabaseTokenOutputWithContext(ctx context.Context) DatabaseTokenOutput {
	return o
}

// The authorization level for the token. Defaults to full-access if not specified.
func (o DatabaseTokenOutput) Authorization() DatabaseTokenAuthorizationPtrOutput {
	return o.ApplyT(func(v *DatabaseToken) DatabaseTokenAuthorizationPtrOutput { return v.Authorization }).(DatabaseTokenAuthorizationPtrOutput)
}

// The name of the database to create the token for.
func (o DatabaseTokenOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseToken) pulumi.StringOutput { return v.Database }).(pulumi.StringOutput)
}

// The duration until the token expires (e.g., '24h', '7d', '30d'). If not specified, the token will not expire.
func (o DatabaseTokenOutput) Expiration() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseToken) pulumi.StringPtrOutput { return v.Expiration }).(pulumi.StringPtrOutput)
}

// The RFC3339 timestamp when the token expires, if an expiration was set.
func (o DatabaseTokenOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DatabaseToken) pulumi.StringPtrOutput { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// List of databases that can be attached for read operations using this token.
func (o DatabaseTokenOutput) ReadAttach() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DatabaseToken) pulumi.StringArrayOutput { return v.ReadAttach }).(pulumi.StringArrayOutput)
}

// The JWT token used to authenticate with the database.
func (o DatabaseTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *DatabaseToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

type DatabaseTokenArrayOutput struct{ *pulumi.OutputState }

func (DatabaseTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DatabaseToken)(nil)).Elem()
}

func (o DatabaseTokenArrayOutput) ToDatabaseTokenArrayOutput() DatabaseTokenArrayOutput {
	return o
}

func (o DatabaseTokenArrayOutput) ToDatabaseTokenArrayOutputWithContext(ctx context.Context) DatabaseTokenArrayOutput {
	return o
}

func (o DatabaseTokenArrayOutput) Index(i pulumi.IntInput) DatabaseTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DatabaseToken {
		return vs[0].([]*DatabaseToken)[vs[1].(int)]
	}).(DatabaseTokenOutput)
}

type DatabaseTokenMapOutput struct{ *pulumi.OutputState }

func (DatabaseTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DatabaseToken)(nil)).Elem()
}

func (o DatabaseTokenMapOutput) ToDatabaseTokenMapOutput() DatabaseTokenMapOutput {
	return o
}

func (o DatabaseTokenMapOutput) ToDatabaseTokenMapOutputWithContext(ctx context.Context) DatabaseTokenMapOutput {
	return o
}

func (o DatabaseTokenMapOutput) MapIndex(k pulumi.StringInput) DatabaseTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DatabaseToken {
		return vs[0].(map[string]*DatabaseToken)[vs[1].(string)]
	}).(DatabaseTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseTokenInput)(nil)).Elem(), &DatabaseToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseTokenArrayInput)(nil)).Elem(), DatabaseTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DatabaseTokenMapInput)(nil)).Elem(), DatabaseTokenMap{})
	pulumi.RegisterOutputType(DatabaseTokenOutput{})
	pulumi.RegisterOutputType(DatabaseTokenArrayOutput{})
	pulumi.RegisterOutputType(DatabaseTokenMapOutput{})
}
