// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Turso.Time.Inputs
{

    public sealed class TimeArgs : global::Pulumi.ResourceArgs
    {
        public TimeArgs()
        {
        }
        public static new TimeArgs Empty => new TimeArgs();
    }
}
