// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/celest-dev/pulumi-turso/sdk/go/turso/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The Turso API token. Can also be set via the TURSO_API_TOKEN environment variable. If not provided, the provider will attempt to use the Turso CLI authentication.
func GetApiToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "turso:apiToken")
}

// The Turso organization slug. Can also be set via the TURSO_ORGANIZATION environment variable.
func GetOrganization(ctx *pulumi.Context) string {
	return config.Get(ctx, "turso:organization")
}
