# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .database import *
from .group import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_turso.config as __config
    config = __config
    import pulumi_turso.time as __time
    time = __time
else:
    config = _utilities.lazy_import('pulumi_turso.config')
    time = _utilities.lazy_import('pulumi_turso.time')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "turso",
  "mod": "index",
  "fqn": "pulumi_turso",
  "classes": {
   "turso:index:Database": "Database",
   "turso:index:Group": "Group"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "turso",
  "token": "pulumi:providers:turso",
  "fqn": "pulumi_turso",
  "class": "Provider"
 }
]
"""
)
