# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'DatabaseSeedType',
]


class DatabaseSeedType(str, Enum):
    DATABASE = "database"
    """
    Uses an database to seed the new database.
    """
    DUMP = "dump"
    """
    Uses a database dump to seed the new database.
    """
