// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const DatabaseSeedType = {
    /**
     * Uses an database to seed the new database.
     */
    Database: "database",
    /**
     * Uses a database dump to seed the new database.
     */
    Dump: "dump",
} as const;

export type DatabaseSeedType = (typeof DatabaseSeedType)[keyof typeof DatabaseSeedType];

export const DatabaseTokenAuthorization = {
    /**
     * Full access to the database
     */
    Full_access: "full-access",
    /**
     * Read only access to the database
     */
    Read_only: "read-only",
} as const;

export type DatabaseTokenAuthorization = (typeof DatabaseTokenAuthorization)[keyof typeof DatabaseTokenAuthorization];

export const GroupTokenAuthorization = {
    /**
     * Full access to the database
     */
    Full_access: "full-access",
    /**
     * Read only access to the database
     */
    Read_only: "read-only",
} as const;

export type GroupTokenAuthorization = (typeof GroupTokenAuthorization)[keyof typeof GroupTokenAuthorization];
