// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const DatabaseSeedType = {
    /**
     * Uses an database to seed the new database.
     */
    Database: "database",
    /**
     * Uses a database dump to seed the new database.
     */
    Dump: "dump",
} as const;

export type DatabaseSeedType = (typeof DatabaseSeedType)[keyof typeof DatabaseSeedType];
