// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Turso.Outputs
{

    [OutputType]
    public sealed class DatabaseInstanceState
    {
        public readonly string Hostname;
        public readonly string Name;
        public readonly string Region;
        public readonly string Type;
        public readonly string Uuid;

        [OutputConstructor]
        private DatabaseInstanceState(
            string hostname,

            string name,

            string region,

            string type,

            string uuid)
        {
            Hostname = hostname;
            Name = name;
            Region = region;
            Type = type;
            Uuid = uuid;
        }
    }
}
