// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface DatabaseSeedArgsArgs {
    /**
     * The name of the database to seed from (when type is 'database') or the URL of the dump file (when type is 'dump').
     */
    name?: pulumi.Input<string>;
    /**
     * A specific point in time to seed from. Only applies when seeding from a database.
     */
    timestamp?: pulumi.Input<inputs.time.TimeArgs>;
    /**
     * The type of seed to use.
     */
    type: pulumi.Input<enums.DatabaseSeedType>;
}
export namespace time {
    export interface TimeArgs {
    }
}
