// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface DatabaseInstanceState {
    /**
     * The hostname of this database instance.
     */
    hostname: string;
    /**
     * The name of this database instance.
     */
    name: string;
    /**
     * The region where this instance is located.
     */
    region: string;
    /**
     * The type of instance (primary or replica).
     */
    type: string;
    /**
     * The unique identifier of this instance.
     */
    uuid: string;
}

export namespace time {
}
