// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Turso.Inputs
{

    public sealed class DatabaseSeedArgsArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("timestamp")]
        public Input<Pulumi.Turso.Time.Inputs.TimeArgs>? Timestamp { get; set; }

        [Input("type", required: true)]
        public Input<Pulumi.Turso.DatabaseSeedType> Type { get; set; } = null!;

        [Input("url")]
        public Input<string>? Url { get; set; }

        public DatabaseSeedArgsArgs()
        {
        }
        public static new DatabaseSeedArgsArgs Empty => new DatabaseSeedArgsArgs();
    }
}
