// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A Turso database. Databases are SQLite databases that live in a group and can be replicated across multiple regions.
 */
export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'turso:index:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    /**
     * Whether read queries to this database are blocked.
     */
    declare public readonly blockReads: pulumi.Output<boolean>;
    /**
     * Whether write queries to this database are blocked.
     */
    declare public readonly blockWrites: pulumi.Output<boolean>;
    /**
     * The unique identifier of the database.
     */
    declare public /*out*/ readonly dbId: pulumi.Output<string>;
    /**
     * Whether deletion protection is enabled for this database.
     */
    declare public /*out*/ readonly deleteProtection: pulumi.Output<boolean>;
    /**
     * The name of the group this database belongs to.
     */
    declare public readonly group: pulumi.Output<string>;
    /**
     * The hostname to connect to this database.
     */
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    /**
     * A map of database instances by region.
     */
    declare public /*out*/ readonly instances: pulumi.Output<{[key: string]: outputs.DatabaseInstanceState}>;
    /**
     * The name of the database.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The primary region where the database is located.
     */
    declare public /*out*/ readonly primaryRegion: pulumi.Output<string>;
    /**
     * All regions where this database has replicas.
     */
    declare public /*out*/ readonly regions: pulumi.Output<string[]>;
    /**
     * The maximum size limit of the database.
     */
    declare public readonly sizeLimit: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatabaseArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.group === undefined && !opts.urn) {
                throw new Error("Missing required property 'group'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["blockReads"] = args?.blockReads;
            resourceInputs["blockWrites"] = args?.blockWrites;
            resourceInputs["group"] = args?.group;
            resourceInputs["name"] = args?.name;
            resourceInputs["seed"] = args?.seed;
            resourceInputs["sizeLimit"] = args?.sizeLimit;
            resourceInputs["dbId"] = undefined /*out*/;
            resourceInputs["deleteProtection"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["instances"] = undefined /*out*/;
            resourceInputs["primaryRegion"] = undefined /*out*/;
            resourceInputs["regions"] = undefined /*out*/;
        } else {
            resourceInputs["blockReads"] = undefined /*out*/;
            resourceInputs["blockWrites"] = undefined /*out*/;
            resourceInputs["dbId"] = undefined /*out*/;
            resourceInputs["deleteProtection"] = undefined /*out*/;
            resourceInputs["group"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["instances"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["primaryRegion"] = undefined /*out*/;
            resourceInputs["regions"] = undefined /*out*/;
            resourceInputs["sizeLimit"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    /**
     * When true, read queries to this database will be blocked.
     */
    blockReads?: pulumi.Input<boolean>;
    /**
     * When true, write queries to this database will be blocked.
     */
    blockWrites?: pulumi.Input<boolean>;
    /**
     * The name of the group where the database belongs. The group must already exist.
     */
    group: pulumi.Input<string>;
    /**
     * The name of the database. Must be unique within the organization.
     */
    name: pulumi.Input<string>;
    /**
     * Configuration for seeding the database from an existing database or dump.
     */
    seed?: pulumi.Input<inputs.DatabaseSeedArgsArgs>;
    /**
     * The maximum size of the database in bytes. You can use units like '1gb', '500mb', etc.
     */
    sizeLimit?: pulumi.Input<string>;
}
