// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * An authentication token for a Turso group. Tokens can be used to connect to any database in the group with specific permissions.
 */
export class GroupToken extends pulumi.CustomResource {
    /**
     * Get an existing GroupToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): GroupToken {
        return new GroupToken(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'turso:index:GroupToken';

    /**
     * Returns true if the given object is an instance of GroupToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GroupToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GroupToken.__pulumiType;
    }

    /**
     * The authorization level for the token. Defaults to full-access if not specified.
     */
    declare public readonly authorization: pulumi.Output<enums.GroupTokenAuthorization | undefined>;
    /**
     * The duration until the token expires (e.g., '24h', '7d', '30d'). If not specified, the token will not expire.
     */
    declare public readonly expiration: pulumi.Output<string | undefined>;
    /**
     * The RFC3339 timestamp when the token expires, if an expiration was set.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<string | undefined>;
    /**
     * The name of the group to create the token for.
     */
    declare public readonly group: pulumi.Output<string>;
    /**
     * List of databases that can be attached for read operations using this token.
     */
    declare public readonly readAttach: pulumi.Output<string[] | undefined>;
    /**
     * The JWT token used to authenticate with databases in the group.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;

    /**
     * Create a GroupToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupTokenArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.group === undefined && !opts.urn) {
                throw new Error("Missing required property 'group'");
            }
            resourceInputs["authorization"] = args?.authorization;
            resourceInputs["expiration"] = args?.expiration;
            resourceInputs["group"] = args?.group;
            resourceInputs["readAttach"] = args?.readAttach;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        } else {
            resourceInputs["authorization"] = undefined /*out*/;
            resourceInputs["expiration"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["group"] = undefined /*out*/;
            resourceInputs["readAttach"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(GroupToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a GroupToken resource.
 */
export interface GroupTokenArgs {
    /**
     * The authorization level for the token. Defaults to full-access if not specified.
     */
    authorization?: pulumi.Input<enums.GroupTokenAuthorization>;
    /**
     * The duration until the token expires (e.g., '24h', '7d', '30d'). If not specified, the token will not expire.
     */
    expiration?: pulumi.Input<string>;
    /**
     * The name of the group to create the token for.
     */
    group: pulumi.Input<string>;
    /**
     * List of databases that can be attached for read operations using this token.
     */
    readAttach?: pulumi.Input<pulumi.Input<string>[]>;
}
